language: python
dist: xenial
sudo: required
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install: "pip install . 'coverage<4' coveralls"
# command to run tests
script:
  coverage run --source=pytimeparse setup.py test
after_success:
  coveralls
