language: python
dist: xenial
sudo: required
python:
  - 3.5
  - 3.6
  - 3.7
# command to install dependencies
install: "pip install . 'coverage<4' coveralls"
# command to run tests
script:
  coverage run --source=pytimeparse setup.py test
after_success:
  coveralls
